### ISSUE TITLE
这个编译不了

### ISSUE THREAD

**Issue by n1test** [rrrfff/javawp#1]
你好。这个可以给一份完整源码学习一下吗？？？

**Comment by Rprop** [comment]
抱歉时间太久源码没有了, 实际上它只是HOOK了javaw.exe的GetSystemTimeAsFileTime

**Comment by n1test** [comment]
请教一下，javawp.exe是java.exe的调用程序吗？ 通过-agentpath 调用的javap.dll还是？？

**Comment by n1test** [comment]
好的，谢谢
